name: BlurCraftStore
description: A modified version of BuycraftX plugin to work better with Geyser. Expects geyser prefix 'BR-', users should use 'BR_' on the store. This will handle the conversion
main: net.buycraft.plugin.bukkit.BuycraftPlugin
version: ${project.version}
authors:
  - Buycraft
  - Serophots
api-version: "1.13"
commands:
  tebex:
    aliases: [buycraft]
    description: Main command for the Tebex plugin.